# Generated by Django 5.2.7 on 2025-10-14 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('name', models.CharField(max_length=127)),
                ('olive_community_id', models.IntegerField()),
                ('olive_title_id', models.IntegerField()),
                ('community_id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1000)])),
                ('description', models.CharField(max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_redesigned', models.BooleanField(default=False)),
                ('appdata', models.BinaryField(null=True)),
                ('block_swears', models.BooleanField(default=False)),
                ('console', models.TextField(null=True)),
                ('badge', models.TextField(null=True)),
                ('platform_name', models.TextField(null=True)),
                ('maxpostlength', models.IntegerField(default=400, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(400)])),
                ('maxcommentlength', models.IntegerField(default=400, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(400)])),
            ],
        ),
    ]
