# Generated by Django 5.2.7 on 2025-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='offdevice_banner',
            field=models.ImageField(default='community_banners/default.png', upload_to='community_banners/'),
        ),
        migrations.AddField(
            model_name='community',
            name='offdevice_icon',
            field=models.ImageField(default='community_icons/default.png', upload_to='community_icons/'),
        ),
    ]
