# Generated by Django 5.2.7 on 2025-10-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0002_community_offdevice_banner_community_offdevice_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
