# Generated by Django 5.2.7 on 2025-10-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0003_alter_community_community_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='is_usercreated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='appdata',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='badge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='community_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='console',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='platform_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
