# Generated by Django 5.2.7 on 2025-10-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0004_community_is_special_community_is_usercreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='author_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
