# Generated by Django 5.2.7 on 2025-10-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0005_community_author_id_community_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_community_id',
            field=models.IntegerField(default=6402030939880837656),
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_title_id',
            field=models.IntegerField(default=6491562013914825089),
        ),
    ]
