# Generated by Django 5.2.7 on 2025-10-15 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0006_alter_community_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='olive_community_id',
            field=models.IntegerField(default=6455146863070641101),
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_title_id',
            field=models.IntegerField(default=6498174577232908129),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfp_method', models.TextField(blank=True, null=True)),
                ('pfp_value', models.TextField(blank=True, null=True)),
                ('mii_name', models.CharField(blank=True, max_length=127, null=True)),
                ('bio', models.CharField(blank=True, max_length=2200, null=True)),
                ('follower_count', models.IntegerField()),
                ('follow_count', models.IntegerField()),
                ('game_experience', models.TextField(blank=True, null=True)),
                ('post_count', models.IntegerField()),
                ('yeah_count', models.IntegerField()),
                ('karma', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
