# Generated by Django 5.2.7 on 2025-10-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0008_alter_community_maxpostlength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='has_badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_community_id',
            field=models.IntegerField(default=6492016750165616795),
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_title_id',
            field=models.IntegerField(default=6416293986339655267),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.TextField(default='AYMHAAAsu1puwp58zp04fh'),
        ),
    ]
