# Generated by Django 5.2.7 on 2025-10-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0009_community_has_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feeling',
            field=models.TextField(default='normal'),
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_community_id',
            field=models.IntegerField(default=6491036368762592217),
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_title_id',
            field=models.IntegerField(default=6442145906917711584),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.TextField(default='AYMHAAAe8c4znkop5bf6f8'),
        ),
    ]
