# Generated by Django 5.2.7 on 2025-10-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0010_post_feeling_alter_community_olive_community_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_spoiler',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_community_id',
            field=models.IntegerField(default=6473370881310260634),
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_title_id',
            field=models.IntegerField(default=6435912368254691294),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.TextField(default='AYMHAAAbnxh33rtj3mulz1'),
        ),
    ]
