# Generated by Django 5.2.7 on 2025-10-18 16:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0011_post_is_spoiler_alter_community_olive_community_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_community_id',
            field=models.IntegerField(default=6461930134202907876),
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_title_id',
            field=models.IntegerField(default=6406140583207653480),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.TextField(default='AYMHAAAnffyd0b0w766z69'),
        ),
        migrations.CreateModel(
            name='Post_Yeah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kamekverse.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
