# Generated by Django 5.2.7 on 2025-10-19 10:48

import django.db.models.deletion
import kamekverse.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0012_post_creation_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='olive_community_id',
            field=models.IntegerField(default=kamekverse.models.olive_ids),
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_title_id',
            field=models.IntegerField(default=kamekverse.models.olive_ids),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.TextField(default=kamekverse.models.post_ids),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.TextField(default=kamekverse.models.post_ids)),
                ('text', models.CharField(max_length=400)),
                ('yeahs', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('feeling', models.TextField(default='normal')),
                ('is_spoiler', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kamekverse.post')),
            ],
        ),
    ]
