# Generated by Django 5.2.7 on 2025-10-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0014_post_nahs_post_nah'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_file',
            field=models.ImageField(blank=True, null=True, upload_to='post_files/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/sampler_placeholder.png', upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_file',
            field=models.ImageField(blank=True, null=True, upload_to='post_files/'),
        ),
    ]
