# Generated by Django 5.2.7 on 2025-10-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0016_post_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform_Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='community_flair_icons/null.png', upload_to='community_flair_icons/')),
            ],
        ),
    ]
