# Generated by Django 5.2.7 on 2025-10-23 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0017_platform_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='console',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kamekverse.platform_badge'),
        ),
    ]
