# Generated by Django 5.2.7 on 2025-10-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0018_alter_community_console'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_badge',
            name='name',
            field=models.CharField(default='Unnamed Badge', max_length=127),
        ),
    ]
