# Generated by Django 5.2.7 on 2025-10-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0019_platform_badge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='featured_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kamekverse.post'),
        ),
    ]
