# Generated by Django 5.2.7 on 2025-10-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0020_profile_discord_profile_featured_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ban',
            field=models.BooleanField(default=False),
        ),
    ]
