# Generated by Django 5.2.7 on 2025-10-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0021_profile_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend_count',
            field=models.IntegerField(default=0),
        ),
    ]
