# Generated by Django 5.2.7 on 2025-10-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0022_profile_friend_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='game_experience',
            field=models.TextField(default='beginner'),
        ),
    ]
