# Generated by Django 5.2.7 on 2025-10-26 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0025_comment_nah_comment_yeah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_nah',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment_yeah',
            name='post',
        ),
        migrations.AddField(
            model_name='comment_nah',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kamekverse.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment_yeah',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kamekverse.comment'),
            preserve_default=False,
        ),
    ]
