# Generated by Django 5.2.7 on 2025-10-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0026_remove_comment_nah_post_remove_comment_yeah_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nahs',
            field=models.IntegerField(default=0),
        ),
    ]
