# Generated by Django 5.2.7 on 2025-10-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0027_comment_nahs'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
