# Generated by Django 5.2.7 on 2025-11-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0028_community_allow_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='screenshot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
