# Generated by Django 5.2.7 on 2025-11-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0029_post_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='screenshot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
