# Generated by Django 5.2.7 on 2025-11-07 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0030_comment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_multilanguage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='maxcommentlength',
            field=models.IntegerField(default=2200, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2200)]),
        ),
        migrations.AlterField(
            model_name='community',
            name='maxpostlength',
            field=models.PositiveIntegerField(default=2200, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2200)]),
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_title_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=2200),
        ),
    ]
