# Generated by Django 5.2.7 on 2025-11-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0031_post_is_multilanguage_alter_comment_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_0',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_1',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_10',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_2',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_3',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_4',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_5',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_6',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_7',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_8',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_9',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
    ]
