# Generated by Django 5.2.7 on 2025-11-27 18:51

import django.db.models.deletion
import kamekverse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0032_remove_post_text_post_body_post_body_0_post_body_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('title_id', models.IntegerField(default=kamekverse.models.olive_ids)),
                ('offdevice_icon', models.ImageField(default='community_icons/default.png', upload_to='title_icons/')),
                ('offdevice_banner', models.ImageField(blank=True, null=True, upload_to='title_banners/')),
            ],
        ),
        migrations.AlterField(
            model_name='community',
            name='offdevice_banner',
            field=models.ImageField(blank=True, null=True, upload_to='community_banners/'),
        ),
        migrations.AddField(
            model_name='community',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kamekverse.title'),
        ),
    ]
