# Generated by Django 5.2.7 on 2025-11-27 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0033_title_alter_community_offdevice_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='console',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kamekverse.platform_badge'),
        ),
        migrations.AddField(
            model_name='title',
            name='platform_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
