# Generated by Django 5.2.7 on 2025-11-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0034_title_console_title_platform_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('css', models.FileField(upload_to='')),
                ('files', models.FilePathField()),
            ],
        ),
    ]
