# Generated by Django 5.2.7 on 2025-11-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0035_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='files',
        ),
    ]
