# Generated by Django 5.2.7 on 2025-11-27 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0036_remove_theme_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kamekverse.theme'),
        ),
    ]
