# Generated by Django 5.2.7 on 2025-11-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0037_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.FileField(upload_to='themecss/'),
        ),
    ]
