# Generated by Django 5.2.7 on 2025-11-27 19:41

import kamekverse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0038_alter_theme_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='tid',
            field=models.TextField(default=kamekverse.models.post_ids),
        ),
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.FileField(upload_to='themecss/<django.db.models.fields.TextField>'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.TextField(),
        ),
    ]
