# Generated by Django 5.2.7 on 2025-11-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0039_theme_tid_alter_theme_css_alter_theme_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='css',
        ),
    ]
