# Generated by Django 5.2.7 on 2025-11-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0040_remove_theme_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='css',
            field=models.FileField(default='noutendo.css', upload_to='themecss/<bound method Field.value_from_object of <django.db.models.fields.TextField>>'),
            preserve_default=False,
        ),
    ]
