# Generated by Django 5.2.7 on 2025-11-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0041_theme_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.FileField(upload_to='themecss/<function post_ids at 0x000002DD2A7C7600>'),
        ),
    ]
