# Generated by Django 5.2.7 on 2025-11-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0043_alter_theme_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.FileField(upload_to='themecss/<function post_ids at 0x0000014C3C63ADE0>'),
        ),
    ]
