# Generated by Django 5.2.7 on 2025-12-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0045_alter_theme_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='themecolor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.FileField(upload_to='themecss/<function post_ids at 0x000001E55F2D6DE0>'),
        ),
    ]
