# Generated by Django 5.2.7 on 2025-12-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0046_profile_themecolor_alter_theme_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.FileField(upload_to='themecss/<function post_ids at 0x00000111EB0A6DE0>'),
        ),
    ]
