# Generated by Django 5.2.7 on 2026-01-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0049_alter_theme_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.FileField(upload_to='themecss/8092155718771'),
        ),
    ]
