# Generated by Django 5.2.7 on 2026-01-06 20:27

import kamekverse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0051_rename_text_comment_body_alter_theme_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='olive_community_id',
            field=models.BigIntegerField(default=kamekverse.models.olive_ids),
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_title_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.FileField(upload_to=kamekverse.models.themeurls),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_id',
            field=models.BigIntegerField(default=kamekverse.models.olive_ids),
        ),
    ]
