# Generated by Django 5.2.7 on 2026-01-17 13:40

import kamekverse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0053_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='olive_community_id',
            field=models.TextField(default=kamekverse.models.olive_ids),
        ),
        migrations.AlterField(
            model_name='community',
            name='olive_title_id',
            field=models.TextField(default=0),
        ),
    ]
