# Generated by Django 5.2.7 on 2026-06-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0058_alter_post_image_api_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.ManyToManyField(blank=True, to='kamekverse.theme'),
        ),
    ]
