# Generated by Django 5.2.7 on 2026-06-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0059_remove_profile_theme_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
