# Generated by Django 5.2.7 on 2026-06-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0060_theme_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='themes_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
