# Generated by Django 5.2.7 on 2026-06-07 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0061_profile_themes_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='badges/')),
                ('name', models.CharField(default='Unnamed Badge', max_length=127)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kamekverse.user_badge'),
        ),
    ]
