# Generated by Django 5.2.7 on 2026-06-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0062_user_badge_profile_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
