# Generated by Django 5.2.7 on 2026-06-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0063_profile_name_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name_color',
            new_name='name_color_1',
        ),
        migrations.AddField(
            model_name='profile',
            name='name_color_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
