# Generated by Django 5.2.7 on 2026-06-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0064_rename_name_color_profile_name_color_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name_color_1',
            field=models.TextField(blank=True, default='#000000'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_color_2',
            field=models.TextField(blank=True, default='#000000'),
        ),
    ]
