# Generated by Django 5.2.7 on 2026-06-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0065_alter_profile_name_color_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_name_color',
            field=models.BooleanField(default=False),
        ),
    ]
