# Generated by Django 5.2.7 on 2026-06-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamekverse', '0067_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
